services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR
      - SERVER_URL
      - FRONTEND_URL

    depends_on:
      - redis

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - ":6379"
