services:
  backend:
    image: yoshikazuuu/url-shortener-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - backend/.env  # Load the backend environment variables
    depends_on:
      - redis

  frontend:
    image: yoshikazuuu/url-shortener-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env  # Load the frontend environment variables
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
