services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env  # Load the backend environment variables
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
