services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - HOST_URL=${HOST_URL}
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
